### ISSUE TITLE
Priority 11 - Mouse click is not working in all mifos tabs (like account details, repayment schedule tabs)

### ISSUE THREAD

**Issue by MathiDuruva** [mifos-x-customization/temp-os#8] opened 2019-08-31 11:26 UTC
If i want to select the account details tab in the loan page, sometimes my mouse click is not working. All i have to do is use "Tab+enter" for navigation.

**Comment by maektwain** [comment] 2019-10-15 08:08
I cannot reproduce this issue at all. So closing this. I didn't face anything as such.
Thanks

**Closed as completed by maektwain** 2019-10-15 08:08 UTC
